import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { LoadingProvider } from "@/app/context/LoadingContext";
import AppWrapper from "@/components/AppWrapper";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Vox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spaceGrotesk.variable}>
      <body className="antialiased">
        <AuthProvider>
          <LoadingProvider>
            <AppWrapper>
              {children}
            </AppWrapper>
          </LoadingProvider>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
